---
title: Hello World
author: RQ
date: '2019-03-03'
slug: hello-world
categories: []
tags: []
image:
  caption: ''
  focal_point: ''
---

This is my very first blog post using the academic layout.
I hope, I can finally fix the problem and run it.

In principle I followed the great "up and running" tutorial.
However, I ran into 2 major issues that made me curse for a while.
Hence, I put this upfront. Make sure you recall this.

1. following the initial installation and some adaptation, RStudio froze when I tried to commit and push to github. There are various discussions on the internet, but none really helped me. If you read some of the tutorials, you will also realise that quite some people use the command line for the initial git operations. Long story short: Do not do your first commit and push with RStudio. Simply open the git shell and type

```
git add .   # stage all files
git commit -m "put a meaningful commit message here like 'my first blogdown commit'"
git push origin master
```

you will see quite some files flying by. This seems to be the source of the problem. The RStudio git support seems to hang up, if the commit comprises a high number of files.

Note: apparently, you can also use RStudio push (arrow up), once you did the staging and commit in the shell.

2. netlify continued deployment: I have to admit this was a bit of a lapse on my side. I did not pay too much attention to what hugo version was installed on my development computer. When configuring netlify, I used the options given (in my case HUGO_VERSION with a value of 0.42).
The deploys failed on netlify while on my computer all was running and displaying nicely :(

I had to google for quite a while before coming across [Katie Scranton's blog](http://www.katherinescranton.com/post/building-my-website-with-blogdown/).
Katie referred to cross-checking the hugo version with

```
blogdown::hugo_version()
```

I got the following result: '0.54.0'. As you can see, changing the value in netlify to this HUGO_VERSION made my day and my site works properly.



In principle, I followed the steps laid out by [Alison](https://alison.rbind.io/post/up-and-running-with-blogdown/#build-your-site-in-rstudio). 