---
title: Zotero and RMarkdown
author: RQ
date: '2019-08-08'
slug: zotero-and-rmarkdown
categories: []
tags:
  - R Markdown
  - zotero
  - how-to
image:
  caption: ''
  focal_point: ''
---

If you are only interested in the how-to, skip the first section of this post.
This blog post supports the good points made by [Christopher]( https://christopherjunk.netlify.com/blog/2019/02/25/zotero-rmarkdown/)

# Writing Paper and Managing References

Every researcher will have a story to tell about the time invested in getting the references for a paper or report right.
After all those years I am still surprised how much emphasis is given to the list of references, and whether it is well formatted.
The focus and energy of an author should be on the content.
While I accept that a well-researched paper and the trait of our trade require an accurate separation between own contributions and ideas build on the research of others, I struggle to see the point why we have this avalanche of differences in reference formats ... not just between different disciplines that might have slightly diverging school of thoughts ... but also with the same discipline. If you do not believe me, take a closer look at the "variances" of referencing standards in IEEE.

If you love Rmarkdown, you will love BibTex. Although writing BibTex properly is an art in itself as well. Still the benefits are having a human readable plain-text database of your references.
And thanks god there are a variety of BibTex editors that take away the burden of mastering the many curly brackets, fields, etc. that BibTex requires.
I started my BibTex career with JabRef which is a Java based application.
A couple of years ago I changed to Zotero. Primarily because it come with a web-database that allows you to collaborate with others online and removes the burden of synching between different contributors.

One of the key features of Zotero is that you can extract references and keep them updated while you work on a paper or report.
This means you can truly leverage your way to manage references by maintaining one "master" library ^[or a small set of master libraries, if your job/way of working requires.].

(VERBATIM FROM CHRISTOPHER - EDIT THIS) Put all works that you want to cite into the directory you are working out of in R. I do this by right-clicking a collection on the left-hand panel, selecting “Export Collection”, and make sure you select BibTeX format from the top dropdown menu. Then, simply place it in the directory when your file explorer pops up.
(END VERBATIM)
